# This chain takes 2 inputs
# - config: JSON, the configuration of chimera web framework, at least contains a key, 'mongo_url'
# - table: String, the table name
# The output will be a JSON for config structure

ins: config, table
out: output
verbose: true
series:
    - (config.mongo_url, table) -> (url, table)=>{return {'mongo_url':url,'history':'_history','table':table}} -> output
