# ======================== GENERAL ==================================
# Uncomment and modify the default settings
# ===================================================================

mongo_url: 'mongodb://localhost/project-template'

# public_path: 'public'
# migration_path: 'chains/migrations'
# favicon_path: 'public/favicon.ico'

# view_path: 'views'
# error_template: 'error.pug'

# session_secret: 'mySecret'
# session_max_age: 60000
# session_save_unitialized: true
# session_resave: true

# login_validation_chain: 'chains/core/is_login.yaml'
# group_validation_chain: 'chains/core/is_in_group.yaml'
# route_list_chain: 'chains/core/route_list.yaml'
# current_version_chain: 'chains/core/current_version.yaml'
# upgrade_version_chain: 'chains/core/upgrade_version.yaml'
# downgrade_version_chain: 'chains/core/downgrade_version.yaml'


# ======================== DEVELOPMENT ===============================

# development.session_secret: 'Secret of my heart'
# development.session_max_age: 30000
